DROP TABLE IF EXISTS Extras;
DROP TABLE IF EXISTS Seats;
DROP TABLE IF EXISTS Tickets;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS DateFlight;
DROP TABLE IF EXISTS Flight;
DROP TABLE IF EXISTS Airline;
